apiVersion: v1
kind: Pod
metadata:
  name: nginx-vol
spec:
  containers:
    - image: bitnami/nginx
      name: nginx
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
        capabilities:
          drop: ["ALL"]
        seccompProfile: 
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /app
          name: nginx-html
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: pvc01